/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/00_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/01_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/02_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/03_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/04_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/05_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/06_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/07_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/08_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/09_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/10_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/11_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/12_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/13_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/14_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/15_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/16_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/17_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/18_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/19_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/20_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/21_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/22_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/23_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/24_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/25_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/26_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/27_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/28_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/29_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/30_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/31_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/32_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/33_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/34_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/35_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/36_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/37_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/38_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/39_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/40_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/41_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/42_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/43_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/44_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/45_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/46_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/47_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/48_result_group.txt
/home/huang/work/EventCounts/remove_trash.sh /windroot/huang/MergeEvent/49_result_group.txt
